from .main_window_shared import *


class SettingsLayoutMixin:
    def build_settings_page(self):
        page = tk.Frame(self.page_container, bg=BG)
        self.pages["settings"] = page
        self.section_title(page, "Настройки", "Простая и рабочая страница: профиль, голос и пути к приложениям.")

        wrap = tk.Frame(page, bg=BG)
        wrap.pack(fill="both", expand=True, padx=12, pady=(8, 12))

        toolbar = tk.Frame(wrap, bg=BG)
        toolbar.pack(fill="x", pady=(0, 10))
        self.make_button(toolbar, "Сохранить настройки", self.save_paths, variant="primary", font=("Segoe UI", 10, "bold"), padx=12, pady=8).pack(side="left", padx=(0, 8))
        self.make_button(toolbar, "Проверить STT", self.test_stt_setup, variant="secondary", font=("Segoe UI", 10, "bold"), padx=12, pady=8).pack(side="left", padx=(0, 8))
        self.make_button(toolbar, "Тест голоса", self.test_voice, variant="ghost", font=("Segoe UI", 10, "bold"), padx=12, pady=8).pack(side="left", padx=(0, 8))
        self.make_button(toolbar, "API-ключ", self.setup_cloud_key_helper, variant="primary", font=("Segoe UI", 10, "bold"), padx=12, pady=8).pack(side="left", padx=(0, 8))
        self.make_button(toolbar, "Установить Ollama", self.setup_local_model_ollama, variant="secondary", font=("Segoe UI", 10, "bold"), padx=12, pady=8).pack(side="left", padx=(0, 8))
        self.make_button(toolbar, "Проверить модель", self.check_local_model_ollama, variant="ghost", font=("Segoe UI", 10, "bold"), padx=12, pady=8).pack(side="left")

        body = tk.Frame(wrap, bg=BG)
        body.pack(fill="both", expand=True)
        left = tk.Frame(body, bg=BG)
        left.pack(side="left", fill="both", expand=True)
        right = tk.Frame(body, bg=BG, width=360)
        right.pack(side="left", fill="y", padx=(12, 0))
        right.pack_propagate(False)

        if not hasattr(self, "user_name_var"):
            self.user_name_var = tk.StringVar(value=self.cfg.get("user_name", "Пользователь"))
        self.path_vars = {}

        model_top = self.card(left, bg=CARD_ALT)
        model_top.pack_propagate(True)
        model_top.pack(fill="x", pady=(0, 10))
        tk.Label(model_top, text="Ответы через модель", bg=CARD_ALT, fg=ACCENT, font=("Segoe UI", 16, "bold")).pack(anchor="w", padx=16, pady=(14, 6))
        tk.Label(model_top, text="Здесь выбирается режим ответов: локальный Ollama, облачный провайдер по своему ключу или автоматический выбор. Локальные команды работают независимо от выбранного режима ответов.", bg=CARD_ALT, fg=MUTED, font=("Segoe UI", 10), wraplength=760, justify="left").pack(anchor="w", padx=16, pady=(0, 6))
        tk.Label(model_top, text="Для быстрой настройки можно использовать кнопки на верхней панели.", bg=CARD_ALT, fg=WARN, font=("Segoe UI", 9, "bold"), wraplength=760, justify="left").pack(anchor="w", padx=16, pady=(0, 10))

        row_provider_top = tk.Frame(model_top, bg=CARD_ALT)
        row_provider_top.pack(fill="x", padx=16, pady=(0, 8))
        tk.Label(row_provider_top, text="Режим", width=13, anchor="w", bg=CARD_ALT, fg=TEXT, font=("Segoe UI", 10, "bold")).pack(side="left")
        ttk.Combobox(row_provider_top, textvariable=self.model_provider_var, values=["auto", "local", "cloud"], state="readonly").pack(side="left", fill="x", expand=True)
        tk.Label(row_provider_top, text=" auto = ключ есть → облачный режим, ключа нет → Ollama", bg=CARD_ALT, fg=MUTED, font=("Segoe UI", 9)).pack(side="left", padx=(10, 0))

        tk.Label(model_top, text="Ключ облачного режима", bg=CARD_ALT, fg=TEXT, font=("Segoe UI", 10, "bold")).pack(anchor="w", padx=16)
        top_key_entry = tk.Entry(model_top, textvariable=self.cloud_api_key_var, show="*")
        self.style_entry_widget(top_key_entry, font=("Segoe UI", 11))
        top_key_entry.pack(fill="x", padx=16, pady=(4, 10), ipady=8)

        row_model_buttons_top = tk.Frame(model_top, bg=CARD_ALT)
        row_model_buttons_top.pack(fill="x", padx=16, pady=(0, 14))
        self.make_button(row_model_buttons_top, "Сохранить ключ / настройки", self.save_paths, variant="primary", font=("Segoe UI", 10, "bold"), padx=12, pady=8).pack(side="left", padx=(0, 8))
        self.make_button(row_model_buttons_top, "Вставить ключ", self.setup_cloud_key_helper, variant="secondary", font=("Segoe UI", 10, "bold"), padx=12, pady=8).pack(side="left", padx=(0, 8))
        self.make_button(row_model_buttons_top, "Подготовить локальный режим", self.setup_local_model_ollama, variant="secondary", font=("Segoe UI", 10, "bold"), padx=12, pady=8).pack(side="left", padx=(0, 8))
        self.make_button(row_model_buttons_top, "Проверить модель", self.check_local_model_ollama, variant="ghost", font=("Segoe UI", 10, "bold"), padx=12, pady=8).pack(side="left")

        profile = self.card(left)
        profile.pack_propagate(True)
        profile.pack(fill="x", pady=(0, 10))
        tk.Label(profile, text="Профиль", bg=CARD, fg=TEXT, font=("Segoe UI", 14, "bold")).pack(anchor="w", padx=16, pady=(14, 8))
        tk.Label(profile, text="Имя пользователя", bg=CARD, fg=MUTED, font=("Segoe UI", 9)).pack(anchor="w", padx=16)
        e = tk.Entry(profile, textvariable=self.user_name_var)
        self.style_entry_widget(e, font=("Segoe UI", 11))
        e.pack(fill="x", padx=16, pady=(4, 12), ipady=8)
        tk.Label(profile, text="Имя ассистента в окне берётся из профиля после сохранения.", bg=CARD, fg=MUTED, font=("Segoe UI", 9), wraplength=700, justify="left").pack(anchor="w", padx=16, pady=(0, 14))

        apps = self.card(left)
        apps.pack_propagate(True)
        apps.pack(fill="x", pady=(0, 10))
        tk.Label(apps, text="Пути к приложениям", bg=CARD, fg=TEXT, font=("Segoe UI", 14, "bold")).pack(anchor="w", padx=16, pady=(14, 8))
        for key, title in [("telegram_path", "Telegram"), ("discord_path", "Discord"), ("steam_path", "Steam")]:
            row = tk.Frame(apps, bg=CARD)
            row.pack(fill="x", padx=16, pady=6)
            tk.Label(row, text=title, width=10, anchor="w", bg=CARD, fg=TEXT, font=("Segoe UI", 10, "bold")).pack(side="left")
            var = tk.StringVar(value=self.cfg.get(key, ""))
            self.path_vars[key] = var
            entry = tk.Entry(row, textvariable=var)
            self.style_entry_widget(entry, font=("Segoe UI", 10))
            entry.pack(side="left", fill="x", expand=True, padx=(0, 8), ipady=6)
            self.make_button(row, "Выбрать", lambda k=key: self.pick_path(k), variant="secondary", font=("Segoe UI", 9, "bold"), padx=10, pady=6).pack(side="left", padx=(0, 6))
            self.make_button(row, "Найти", lambda k=key: self.auto_find_single(k), variant="ghost", font=("Segoe UI", 9, "bold"), padx=10, pady=6).pack(side="left")

        voice = self.card(left)
        voice.pack_propagate(True)
        voice.pack(fill="x", pady=(0, 10))
        tk.Label(voice, text="Голос", bg=CARD, fg=TEXT, font=("Segoe UI", 14, "bold")).pack(anchor="w", padx=16, pady=(14, 8))
        tk.Checkbutton(voice, text="Запускать голос автоматически при старте JARVIS", variable=self.auto_start_voice_var, bg=CARD, fg=TEXT, activebackground=CARD, activeforeground=TEXT, selectcolor=CARD, font=("Segoe UI", 10, "bold")).pack(anchor="w", padx=16, pady=(0, 8))
        tk.Label(voice, text="Режим озвучки", bg=CARD, fg=MUTED, font=("Segoe UI", 9)).pack(anchor="w", padx=16)
        self.tts_mode_combo = ttk.Combobox(voice, textvariable=self.tts_engine_var, values=["auto", "edge", "system"], state="readonly")
        self.tts_mode_combo.pack(fill="x", padx=16, pady=(4, 10))
        tk.Label(voice, text="Распознавание речи", bg=CARD, fg=MUTED, font=("Segoe UI", 9)).pack(anchor="w", padx=16)
        self.stt_mode_combo = ttk.Combobox(voice, textvariable=self.voice_input_engine_var, values=["auto", "whisper", "whisper_cpp", "vosk", "speechkit"], state="readonly")
        self.stt_mode_combo.pack(fill="x", padx=16, pady=(4, 10))
        tk.Label(voice, text="Модель Whisper", bg=CARD, fg=MUTED, font=("Segoe UI", 9)).pack(anchor="w", padx=16)
        ttk.Combobox(voice, textvariable=self.whisper_model_var, values=["tiny", "base", "small", "medium"], state="readonly").pack(fill="x", padx=16, pady=(4, 10))
        tk.Label(voice, text="Устройство Whisper", bg=CARD, fg=MUTED, font=("Segoe UI", 9)).pack(anchor="w", padx=16)
        ttk.Combobox(voice, textvariable=self.whisper_device_var, values=["auto", "cpu", "cuda"], state="readonly").pack(fill="x", padx=16, pady=(4, 10))
        tk.Label(voice, text="Рекомендуемый режим для обычного запуска: STT = vosk. Автостарт голоса можно отключить галочкой выше.", bg=CARD, fg=MUTED, font=("Segoe UI", 9), wraplength=700, justify="left").pack(anchor="w", padx=16, pady=(0, 14))

        ai = self.card(left)
        ai.pack_propagate(True)
        ai.pack(fill="x", pady=(0, 10))
        tk.Label(ai, text="Ответы через модель", bg=CARD, fg=TEXT, font=("Segoe UI", 14, "bold")).pack(anchor="w", padx=16, pady=(14, 8))
        tk.Checkbutton(ai, text="Включить ответы через модель голосом", variable=self.model_answers_enabled_var, bg=CARD, fg=TEXT, activebackground=CARD, activeforeground=TEXT, selectcolor=CARD, font=("Segoe UI", 10)).pack(anchor="w", padx=16, pady=(0, 4))
        tk.Checkbutton(ai, text="Если команда не распознана — пробовать ответить через модель", variable=self.model_fallback_unknown_var, bg=CARD, fg=TEXT, activebackground=CARD, activeforeground=TEXT, selectcolor=CARD, font=("Segoe UI", 10)).pack(anchor="w", padx=16, pady=(0, 8))

        row_provider = tk.Frame(ai, bg=CARD)
        row_provider.pack(fill="x", padx=16, pady=(0, 10))
        tk.Label(row_provider, text="Режим", width=10, anchor="w", bg=CARD, fg=MUTED, font=("Segoe UI", 9)).pack(side="left")
        ttk.Combobox(row_provider, textvariable=self.model_provider_var, values=["local", "cloud", "auto"], state="readonly").pack(side="left", fill="x", expand=True)

        row_model_setup = tk.Frame(ai, bg=CARD)
        row_model_setup.pack(fill="x", padx=16, pady=(0, 10))
        self.make_button(row_model_setup, "Подготовить локальный режим", self.setup_local_model_ollama, variant="primary", font=("Segoe UI", 10, "bold"), padx=12, pady=8).pack(side="left", padx=(0, 8))
        tk.Label(row_model_setup, text="Поставит Ollama и скачает маленькую модель llama3.2:1b через отдельное окно.", bg=CARD, fg=MUTED, font=("Segoe UI", 9), wraplength=520, justify="left").pack(side="left", fill="x", expand=True)

        row_ollama = tk.Frame(ai, bg=CARD)
        row_ollama.pack(fill="x", padx=16, pady=(0, 10))
        tk.Label(row_ollama, text="Ollama", width=10, anchor="w", bg=CARD, fg=MUTED, font=("Segoe UI", 9)).pack(side="left")
        ttk.Combobox(row_ollama, textvariable=self.ollama_model_var, values=["llama3.2:1b", "llama3.2", "qwen2.5:1.5b", "qwen2.5:3b", "gemma3:1b", "gemma3:4b"], state="normal").pack(side="left", fill="x", expand=True, padx=(0, 8))
        tk.Label(row_ollama, text="Токены", bg=CARD, fg=MUTED, font=("Segoe UI", 9)).pack(side="left", padx=(8, 6))
        tk.Spinbox(row_ollama, from_=120, to=1800, increment=50, textvariable=self.ollama_max_tokens_var, width=7, bg=BG, fg=TEXT, insertbackground=TEXT, relief="flat").pack(side="left")

        tk.Label(ai, text="Адрес Ollama", bg=CARD, fg=MUTED, font=("Segoe UI", 9)).pack(anchor="w", padx=16)
        ollama_url_entry = tk.Entry(ai, textvariable=self.ollama_base_url_var)
        self.style_entry_widget(ollama_url_entry, font=("Segoe UI", 10))
        ollama_url_entry.pack(fill="x", padx=16, pady=(4, 10), ipady=6)

        tk.Label(ai, text="API-ключ облачного режима", bg=CARD, fg=MUTED, font=("Segoe UI", 9)).pack(anchor="w", padx=16)
        key_entry = tk.Entry(ai, textvariable=self.cloud_api_key_var, show="*")
        self.style_entry_widget(key_entry, font=("Segoe UI", 10))
        key_entry.pack(fill="x", padx=16, pady=(4, 10), ipady=6)
        row_cloud = tk.Frame(ai, bg=CARD)
        row_cloud.pack(fill="x", padx=16, pady=(0, 10))
        tk.Label(row_cloud, text="облако", width=10, anchor="w", bg=CARD, fg=MUTED, font=("Segoe UI", 9)).pack(side="left")
        model_combo = ttk.Combobox(row_cloud, textvariable=self.cloud_model_var, values=["gpt-5-mini", "gpt-5-nano", "gpt-4.1-mini", "gpt-4.1-nano"], state="normal")
        model_combo.pack(side="left", fill="x", expand=True, padx=(0, 8))
        tk.Label(row_cloud, text="Токены", bg=CARD, fg=MUTED, font=("Segoe UI", 9)).pack(side="left", padx=(8, 6))
        tk.Spinbox(row_cloud, from_=120, to=1800, increment=50, textvariable=self.cloud_max_tokens_var, width=7, bg=BG, fg=TEXT, insertbackground=TEXT, relief="flat").pack(side="left")
        tk.Label(ai, text="Ключ указывается в поле выше. Для облачного режима выберите cloud или auto. Для локального режима выберите local и один раз нажмите «Подготовить локальный режим».", bg=CARD, fg=MUTED, font=("Segoe UI", 9), wraplength=700, justify="left").pack(anchor="w", padx=16, pady=(0, 14))

        diag = self.card(right, bg=CARD_ALT)
        diag.pack_propagate(True)
        diag.pack(fill="both", expand=True)
        tk.Label(diag, text="Диагностика голоса", bg=CARD_ALT, fg=TEXT, font=("Segoe UI", 14, "bold")).pack(anchor="w", padx=16, pady=(14, 8))
        tk.Label(diag, textvariable=self.tts_state_var, bg=CARD_ALT, fg=ACCENT, font=("Segoe UI", 10, "bold")).pack(anchor="w", padx=16, pady=(0, 4))
        tk.Label(diag, textvariable=self.voice_pipeline_var, bg=CARD_ALT, fg=ACCENT_2, font=("Segoe UI", 9, "bold"), wraplength=300, justify="left").pack(anchor="w", padx=16, pady=(0, 8))
        tk.Checkbutton(diag, text="Показывать уведомления внутри JARVIS", variable=self.toast_notifications_var, bg=CARD_ALT, fg=TEXT, activebackground=CARD_ALT, activeforeground=TEXT, selectcolor=CARD_ALT, font=("Segoe UI", 10)).pack(anchor="w", padx=16, pady=2)
        tk.Checkbutton(diag, text="Уведомления для системных событий", variable=self.system_event_toasts_var, bg=CARD_ALT, fg=TEXT, activebackground=CARD_ALT, activeforeground=TEXT, selectcolor=CARD_ALT, font=("Segoe UI", 10)).pack(anchor="w", padx=16, pady=2)
        self.make_button(diag, "Вкл / выкл голос", self.toggle_tts_enabled, variant="secondary").pack(fill="x", padx=16, pady=(10, 8))
        quick = tk.Frame(diag, bg=CARD_ALT)
        quick.pack(fill="x", padx=16, pady=(0, 8))
        self.make_button(quick, "Диагностика голоса", self.show_voice_diagnostics_center, variant="secondary", font=("Segoe UI", 9, "bold"), padx=10, pady=7).pack(side="left", fill="x", expand=True, padx=(0, 6))
        self.make_button(quick, "Data", self.open_data_dir, variant="ghost", font=("Segoe UI", 9, "bold"), padx=10, pady=7).pack(side="left", fill="x", expand=True, padx=(0, 6))
        self.make_button(quick, "Лог", self.open_system_log_file, variant="ghost", font=("Segoe UI", 9, "bold"), padx=10, pady=7).pack(side="left", fill="x", expand=True)
        self.tts_diag_text = tk.Text(diag, height=16, wrap="word", font=("Consolas", 9))
        self.style_text_widget(self.tts_diag_text)
        self.tts_diag_text.pack(fill="both", expand=True, padx=16, pady=(0, 12))
